# Generated by Django 4.2.30 on 2026-08-09 22:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def backfill_reservation_history(apps, schema_editor):
    Reservation = apps.get_model('reservations', 'Reservation')
    StatusHistory = apps.get_model('reservations', 'ReservationStatusHistory')
    RoomAssignment = apps.get_model('reservations', 'ReservationRoomAssignment')

    for reservation in Reservation.objects.select_related('room', 'room__room_type').iterator():
        nights = max((reservation.check_out_date - reservation.check_in_date).days, 1)
        reservation.price_snapshot = {
            'currency': 'NGN',
            'nightly_rate': str(reservation.nightly_rate),
            'nights': nights,
            'room_type_id': reservation.room.room_type_id,
            'room_type_name': reservation.room.room_type.name,
            'total': str(reservation.total_amount),
            'backfilled': True,
        }
        reservation.policy_snapshot = {'backfilled': True}
        reservation.save(update_fields=['price_snapshot', 'policy_snapshot'])
        history = StatusHistory.objects.create(
            reservation_id=reservation.id,
            from_status='',
            to_status=reservation.status,
            action='migration_backfill',
            actor_id=reservation.created_by_id,
            metadata={'backfilled': True},
        )
        StatusHistory.objects.filter(pk=history.pk).update(created_at=reservation.created_at)
        released_at = reservation.updated_at if reservation.status in {'checked_out', 'cancelled', 'no_show'} else None
        assignment = RoomAssignment.objects.create(
            reservation_id=reservation.id,
            room_id=reservation.room_id,
            assigned_by_id=reservation.created_by_id,
            assigned_at=reservation.created_at,
            released_at=released_at,
            reason='migration_backfill',
        )
        RoomAssignment.objects.filter(pk=assignment.pk).update(assigned_at=reservation.created_at)


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='channel_reference',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='reservation',
            name='policy_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='reservation',
            name='price_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='reservation',
            name='source',
            field=models.CharField(choices=[('direct_website', 'Direct Website'), ('front_desk', 'Front Desk'), ('phone', 'Phone'), ('walk_in', 'Walk In'), ('api', 'API'), ('admin', 'Administration')], default='admin', max_length=30),
        ),
        migrations.CreateModel(
            name='ReservationStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(blank=True, max_length=20)),
                ('to_status', models.CharField(max_length=20)),
                ('action', models.CharField(max_length=30)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservation_status_changes', to=settings.AUTH_USER_MODEL)),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='status_history', to='reservations.reservation')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ReservationRoomAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('reason', models.CharField(default='initial_assignment', max_length=100)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='room_assignments_made', to=settings.AUTH_USER_MODEL)),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='room_assignments', to='reservations.reservation')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservation_assignments', to='rooms.room')),
            ],
            options={
                'ordering': ['assigned_at', 'id'],
            },
        ),
        migrations.RunPython(backfill_reservation_history, noop_reverse),
    ]
