# Generated by Django 4.2.30 on 2026-08-09 22:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_add_rates_quotes_and_holds'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reservations', '0002_add_reservation_history_and_snapshots'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('check_in_date', models.DateField()),
                ('check_out_date', models.DateField()),
                ('num_adults', models.PositiveIntegerField(default=1)),
                ('num_children', models.PositiveIntegerField(default=0)),
                ('currency', models.CharField(default='NGN', max_length=3)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tax_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('price_snapshot', models.JSONField(default=dict)),
                ('policy_snapshot', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('active', 'Active'), ('converted', 'Converted'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='reservation',
            name='rate_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='rooms.rateplan'),
        ),
        migrations.CreateModel(
            name='InventoryHold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('converted', 'Converted'), ('released', 'Released'), ('expired', 'Expired')], default='active', max_length=20)),
                ('expires_at', models.DateTimeField()),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('quote', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hold', to='reservations.bookingquote')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_holds', to='rooms.room')),
            ],
            options={
                'ordering': ['expires_at'],
            },
        ),
        migrations.AddField(
            model_name='bookingquote',
            name='converted_reservation',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='source_quote', to='reservations.reservation'),
        ),
        migrations.AddField(
            model_name='bookingquote',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_booking_quotes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bookingquote',
            name='guest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking_quotes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bookingquote',
            name='rate_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='booking_quotes', to='rooms.rateplan'),
        ),
        migrations.AddField(
            model_name='bookingquote',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='booking_quotes', to='rooms.room'),
        ),
    ]
