# Generated by Django 4.2.30 on 2026-08-10 01:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0004_room_is_sellable_inventoryblock_bookableextra'),
        ('reservations', '0006_reservationdiscountrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingquote',
            name='extra_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.CreateModel(
            name='BookingQuoteExtra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('unit_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('extra', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quote_selections', to='rooms.bookableextra')),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='selected_extras', to='reservations.bookingquote')),
            ],
        ),
        migrations.AddConstraint(
            model_name='bookingquoteextra',
            constraint=models.UniqueConstraint(fields=('quote', 'extra'), name='unique_quote_extra'),
        ),
    ]
