# Generated by Django 4.2.30 on 2026-08-10 01:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def preserve_guest_identity(apps, schema_editor):
    UserProfile = apps.get_model('accounts', 'UserProfile')
    for user in UserProfile.objects.all().iterator():
        email = (user.email or '').strip().lower()
        digits = ''.join(character for character in (user.phone or '') if character.isdigit())
        if len(digits) == 11 and digits.startswith('0'):
            digits = f'234{digits[1:]}'
        elif len(digits) == 10:
            digits = f'234{digits}'
        UserProfile.objects.filter(pk=user.pk).update(
            id_last_four=(user.id_number or '')[-4:],
            normalized_email=email,
            normalized_phone=digits,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='id_last_four',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='merged_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='merged_into',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='merged_guest_accounts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='normalized_email',
            field=models.EmailField(blank=True, db_index=True, max_length=254),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='normalized_phone',
            field=models.CharField(blank=True, db_index=True, max_length=20),
        ),
        migrations.RunPython(preserve_guest_identity, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='userprofile',
            name='id_number',
        ),
        migrations.CreateModel(
            name='GuestMergeHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=255)),
                ('source_snapshot', models.JSONField(default=dict)),
                ('transferred_counts', models.JSONField(default=dict)),
                ('merged_at', models.DateTimeField(auto_now_add=True)),
                ('duplicate_guest', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='guest_merge_record', to=settings.AUTH_USER_MODEL)),
                ('merged_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='performed_guest_merges', to=settings.AUTH_USER_MODEL)),
                ('primary_guest', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='received_guest_merges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-merged_at'],
            },
        ),
    ]
