# Generated by Django 4.2.30 on 2026-08-10 02:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_userprofile_id_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataPrivacyRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('request_type', models.CharField(choices=[('export', 'Access / Export'), ('correction', 'Correction'), ('anonymize', 'Anonymization')], max_length=20)),
                ('details', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed')], default='submitted', max_length=20)),
                ('decision_reason', models.CharField(blank=True, max_length=500)),
                ('artifact', models.FileField(blank=True, upload_to='protected/privacy/%Y/%m/')),
                ('artifact_expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='userprofile',
            name='anonymized_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='privacy_legal_hold',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='DataPrivacyRequestHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=30)),
                ('from_status', models.CharField(blank=True, max_length=20)),
                ('to_status', models.CharField(max_length=20)),
                ('notes', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='privacy_request_actions', to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='history', to='accounts.dataprivacyrequest')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.AddField(
            model_name='dataprivacyrequest',
            name='guest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='privacy_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dataprivacyrequest',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviewed_privacy_requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
