# Generated by Django 5.2.17 on 2026-08-12 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_staffmfadevice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('manager', 'Manager'), ('receptionist', 'Receptionist'), ('accountant', 'Accountant'), ('housekeeping', 'Housekeeping'), ('guest', 'Guest')], default='guest', max_length=20),
        ),
    ]
