# Generated by Django 4.2.30 on 2026-08-09 22:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reservations', '0003_add_rates_quotes_and_holds'),
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Folio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('currency', models.CharField(default='NGN', max_length=3)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('void', 'Void')], default='open', max_length=20)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='folios', to=settings.AUTH_USER_MODEL)),
                ('reservation', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='folio', to='reservations.reservation')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FolioEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('direction', models.CharField(choices=[('debit', 'Debit'), ('credit', 'Credit')], max_length=10)),
                ('entry_type', models.CharField(choices=[('accommodation', 'Accommodation'), ('tax', 'Tax/Fee'), ('service', 'Service'), ('payment', 'Payment'), ('refund', 'Refund'), ('adjustment', 'Adjustment'), ('credit_note', 'Credit Note')], max_length=30)),
                ('description', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('external_key', models.CharField(blank=True, max_length=120, null=True, unique=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('posted_at', models.DateTimeField(auto_now_add=True)),
                ('folio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='billing.folio')),
                ('posted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posted_folio_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['posted_at', 'id'],
            },
        ),
    ]
