# Generated by Django 5.2.17 on 2026-08-13 20:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_financialcorrection'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialAuditRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('run_type', models.CharField(choices=[('daily', 'Daily close'), ('weekly', 'Weekly review'), ('manual', 'Manual review')], default='daily', max_length=12)),
                ('status', models.CharField(choices=[('prepared', 'Prepared'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='prepared', max_length=12)),
                ('metrics', models.JSONField(default=dict)),
                ('exceptions', models.JSONField(default=list)),
                ('source_hash', models.CharField(max_length=64)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('reviewer_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_financial_audits', to=settings.AUTH_USER_MODEL)),
                ('prepared_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prepared_financial_audits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-period_end', '-created_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(('period_end__gte', models.F('period_start'))), name='financial_audit_period_valid'), models.UniqueConstraint(fields=('period_start', 'period_end', 'run_type'), name='financial_audit_period_type_unique')],
            },
        ),
    ]
