# Generated by Django 5.2.17 on 2026-08-14 16:14

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


def preserve_existing_invoice_vat(apps, schema_editor):
    Invoice = apps.get_model('billing', 'Invoice')
    Invoice.objects.filter(tax_rate__gt=0).update(
        vat_amount=models.F('tax_amount'), tax_amount_locked=True,
    )


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_bankaccount_ledgeraccount_bankreconciliation_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='tax_amount_locked',
            field=models.BooleanField(default=False, help_text='Preserves the tax values captured in the reservation price snapshot.'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='vat_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.RunPython(preserve_existing_invoice_vat, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='invoice',
            name='tax_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.CreateModel(
            name='VATRateChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('previous_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('reason', models.CharField(max_length=255)),
                ('effective_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vat_rate_changes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-effective_at', '-id'],
                'constraints': [models.CheckConstraint(condition=models.Q(('rate__gte', 0), ('rate__lte', 100)), name='vat_rate_between_zero_and_hundred')],
            },
        ),
    ]
