# Generated by Django 5.2.17 on 2026-08-17 16:28

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


def seed_expense_categories(apps, schema_editor):
    LedgerAccount = apps.get_model('billing', 'LedgerAccount')
    ExpenseCategory = apps.get_model('billing', 'ExpenseCategory')
    categories = [
        ('5200', 'utilities', 'Utilities'),
        ('5210', 'maintenance', 'Repairs and maintenance'),
        ('5220', 'supplies', 'Guest and operating supplies'),
        ('5230', 'payroll', 'Payroll and staff costs'),
        ('5240', 'marketing', 'Marketing and advertising'),
        ('5250', 'professional-fees', 'Professional fees'),
        ('5290', 'other-operating', 'Other operating expenses'),
    ]
    for ledger_code, category_code, name in categories:
        ledger, _ = LedgerAccount.objects.get_or_create(
            code=ledger_code,
            defaults={
                'name': name,
                'account_type': 'expense',
                'description': 'Controlled operating expenditure account.',
                'is_active': True,
            },
        )
        ExpenseCategory.objects.get_or_create(
            code=category_code,
            defaults={'name': name, 'ledger_account': ledger, 'is_active': True},
        )


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0007_seed_chart_and_backfill_folio_journals'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Expenditure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('business_date', models.DateField(db_index=True, default=django.utils.timezone.localdate)),
                ('vendor', models.CharField(max_length=160)),
                ('description', models.TextField(max_length=1000)),
                ('net_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_amount', models.DecimalField(decimal_places=2, editable=False, max_digits=14)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('pos', 'POS / card'), ('bank_transfer', 'Bank transfer'), ('online', 'Online payment')], max_length=20)),
                ('external_reference', models.CharField(blank=True, max_length=120)),
                ('evidence', models.FileField(blank=True, upload_to='expenditure-evidence/%Y/%m/')),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('paid', 'Paid'), ('void', 'Void')], db_index=True, default='submitted', max_length=12)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_expenditures', to=settings.AUTH_USER_MODEL)),
                ('journal', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expenditure', to='billing.journalentry')),
                ('paid_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='paid_expenditures', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submitted_expenditures', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-business_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExpenditureStatusEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(blank=True, max_length=12)),
                ('to_status', models.CharField(max_length=12)),
                ('note', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('expenditure', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='status_events', to='billing.expenditure')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=40, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ledger_account', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='expense_category', to='billing.ledgeraccount')),
            ],
            options={
                'verbose_name_plural': 'expense categories',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='expenditure',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expenditures', to='billing.expensecategory'),
        ),
        migrations.RunPython(seed_expense_categories, migrations.RunPython.noop),
    ]
