# Generated by Django 5.2.17 on 2026-08-17 16:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0009_alter_expenditure_evidence'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bankreconciliation',
            options={'ordering': ['-period_end', '-created_at']},
        ),
        migrations.AddConstraint(
            model_name='bankreconciliation',
            constraint=models.UniqueConstraint(fields=('bank_account', 'period_start', 'period_end'), name='bank_reconciliation_account_period_unique'),
        ),
    ]
