# Generated by Django 5.2.17 on 2026-08-17 17:03

import apps.billing.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0010_harden_bank_reconciliation_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenditure',
            name='evidence',
            field=models.FileField(blank=True, upload_to='private/expenditure-evidence/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png', 'webp']), apps.billing.models.validate_expenditure_evidence_size]),
        ),
    ]
