# Generated by Django 5.2.17 on 2026-08-17 17:04

from django.db import migrations


def seed_input_vat_account(apps, schema_editor):
    LedgerAccount = apps.get_model('billing', 'LedgerAccount')
    LedgerAccount.objects.get_or_create(
        code='1150',
        defaults={
            'name': 'Input VAT recoverable', 'account_type': 'asset',
            'description': 'VAT paid on approved expenditure, subject to recoverability review.',
            'is_active': True,
        },
    )


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0011_protect_expenditure_evidence_path'),
    ]

    operations = [
        migrations.RunPython(seed_input_vat_account, migrations.RunPython.noop),
    ]
