# Generated by Django 4.2.30 on 2026-08-10 02:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payments', '0002_add_folio_cashiering_and_printing'),
    ]

    operations = [
        migrations.AddField(
            model_name='receiptprintjob',
            name='attempt_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='receiptprintjob',
            name='completed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_receipt_print_jobs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='receiptprintjob',
            name='last_attempt_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
