# Generated by Django 5.2.17 on 2026-08-12 12:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_financialcorrection'),
        ('payments', '0004_backfill_completed_payment_ledgers'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='cashiershift',
            name='one_open_shift_per_terminal',
        ),
        migrations.RemoveConstraint(
            model_name='cashiershift',
            name='one_open_shift_per_cashier',
        ),
        migrations.RenameField(
            model_name='cashiershift',
            old_name='close_note',
            new_name='note',
        ),
        migrations.AddField(
            model_name='cashiershift',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cashiershift',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_cashier_shifts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('cash', 'Cash'), ('bank_transfer', 'Bank Transfer'), ('pos', 'POS Terminal'), ('online', 'Online Gateway')], default='cash', max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='receipt',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_record', to='billing.receipt'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='reference',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
