# Generated by Django 5.2.17 on 2026-08-17 16:55

from django.db import migrations


def seed_terminal(apps, schema_editor):
    CashierTerminal = apps.get_model('payments', 'CashierTerminal')
    CashierTerminal.objects.get_or_create(
        code='front-desk-1',
        defaults={
            'name': 'Front Desk 1', 'location': 'Reception',
            'is_active': True, 'receipt_width_mm': 80,
        },
    )


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_paymentstatusevent'),
    ]

    operations = [
        migrations.RunPython(seed_terminal, migrations.RunPython.noop),
    ]
