# Generated by Django 4.2.30 on 2026-08-10 04:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('housekeeping', '0003_incidentreport_lostfounditem_lostfounditemhistory_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=140)),
                ('category', models.CharField(choices=[('linen', 'Linen'), ('minibar', 'Minibar'), ('housekeeping', 'Housekeeping supply'), ('maintenance', 'Maintenance supply'), ('other', 'Other')], max_length=20)),
                ('unit', models.CharField(default='each', max_length=30)),
                ('reorder_level', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='StockLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=40, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('location_type', models.CharField(choices=[('main_store', 'Main store'), ('floor_store', 'Floor store'), ('front_desk', 'Front desk'), ('outlet', 'Outlet'), ('other', 'Other')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('movement_type', models.CharField(choices=[('receipt', 'Receipt'), ('issue', 'Issue'), ('waste', 'Waste'), ('adjustment_add', 'Positive adjustment'), ('adjustment_remove', 'Negative adjustment'), ('transfer_in', 'Transfer in'), ('transfer_out', 'Transfer out')], max_length=20)),
                ('quantity_delta', models.DecimalField(decimal_places=3, max_digits=14)),
                ('resulting_balance', models.DecimalField(decimal_places=3, max_digits=14)),
                ('transfer_reference', models.UUIDField(blank=True, db_index=True, null=True)),
                ('reason', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='housekeeping.stockitem')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='housekeeping.stocklocation')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='StockBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='balances', to='housekeeping.stockitem')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='balances', to='housekeeping.stocklocation')),
            ],
            options={
                'ordering': ['location__name', 'item__name'],
            },
        ),
        migrations.AddConstraint(
            model_name='stockbalance',
            constraint=models.UniqueConstraint(fields=('item', 'location'), name='unique_item_location_balance'),
        ),
        migrations.AddConstraint(
            model_name='stockbalance',
            constraint=models.CheckConstraint(check=models.Q(('quantity__gte', 0)), name='stock_balance_not_negative'),
        ),
    ]
