# Generated by Django 4.2.30 on 2026-08-09 22:25

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


def create_standard_rate_plans(apps, schema_editor):
    RoomType = apps.get_model('rooms', 'RoomType')
    RatePlan = apps.get_model('rooms', 'RatePlan')
    for room_type in RoomType.objects.iterator():
        RatePlan.objects.get_or_create(
            code=f'standard-{room_type.pk}',
            defaults={
                'room_type_id': room_type.pk,
                'name': 'Standard Rate',
                'description': 'Default flexible room rate.',
                'cancellation_policy': 'Contact the hotel for cancellation terms.',
            },
        )


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('code', models.SlugField(unique=True)),
                ('calculation', models.CharField(choices=[('percentage', 'Percentage'), ('fixed', 'Fixed per stay')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('is_active', models.BooleanField(default=True)),
                ('effective_from', models.DateField(blank=True, null=True)),
                ('effective_to', models.DateField(blank=True, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RatePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('code', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('inclusions', models.JSONField(blank=True, default=list)),
                ('cancellation_policy', models.TextField(blank=True)),
                ('deposit_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('min_stay', models.PositiveIntegerField(default=1)),
                ('max_stay', models.PositiveIntegerField(default=30)),
                ('is_refundable', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rate_plans', to='rooms.roomtype')),
            ],
            options={
                'ordering': ['room_type__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='DailyRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('min_stay', models.PositiveIntegerField(blank=True, null=True)),
                ('closed_to_arrival', models.BooleanField(default=False)),
                ('closed_to_departure', models.BooleanField(default=False)),
                ('rate_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_rates', to='rooms.rateplan')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.AddConstraint(
            model_name='dailyrate',
            constraint=models.UniqueConstraint(fields=('rate_plan', 'date'), name='unique_daily_rate_plan_date'),
        ),
        migrations.RunPython(create_standard_rate_plans, migrations.RunPython.noop),
    ]
