# Generated by Django 4.2.30 on 2026-08-10 01:01

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rooms', '0003_rateplan_cancellation_fee_percent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='is_sellable',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='InventoryBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(help_text='Exclusive end date.')),
                ('reason', models.CharField(choices=[('maintenance', 'Maintenance'), ('owner_use', 'Owner use'), ('renovation', 'Renovation'), ('sales_stop', 'Sales stop'), ('other', 'Other')], max_length=30)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('active', 'Active'), ('released', 'Released')], default='active', max_length=20)),
                ('source_model', models.CharField(blank=True, max_length=80)),
                ('source_id', models.CharField(blank=True, max_length=80)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_inventory_blocks', to=settings.AUTH_USER_MODEL)),
                ('released_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='released_inventory_blocks', to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_blocks', to='rooms.room')),
            ],
            options={
                'ordering': ['start_date', 'room__number'],
            },
        ),
        migrations.CreateModel(
            name='BookableExtra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('pricing_model', models.CharField(choices=[('per_stay', 'Per stay'), ('per_night', 'Per night'), ('per_guest_per_night', 'Per guest per night')], max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('taxable', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('room_types', models.ManyToManyField(blank=True, related_name='bookable_extras', to='rooms.roomtype')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
