# Generated by Django 4.2.30 on 2026-08-10 01:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0004_room_is_sellable_inventoryblock_bookableextra'),
    ]

    operations = [
        migrations.AddField(
            model_name='rateplan',
            name='child_per_night',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='rateplan',
            name='extra_adult_per_night',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='rateplan',
            name='included_adults',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
