# Generated by Django 4.2.30 on 2026-08-10 04:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0005_rateplan_child_per_night_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomTypeImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='room_types/gallery/%Y/%m/')),
                ('alt_text', models.CharField(help_text='Concise visual description for assistive technology.', max_length=180)),
                ('caption', models.CharField(blank=True, max_length=220)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='rooms.roomtype')),
            ],
            options={
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='roomtypeimage',
            constraint=models.UniqueConstraint(condition=models.Q(('is_featured', True)), fields=('room_type',), name='one_featured_image_per_room_type'),
        ),
    ]
