# Generated by Django 5.2.17 on 2026-08-13 15:43

from django.db import migrations, models

def copy_room_type_data_to_rooms(apps, schema_editor):
    Room = apps.get_model('rooms', 'Room')
    for room in Room.objects.all():
        room.price = room.room_type.base_price
        room.image = room.room_type.image
        room.save(update_fields=['price', 'image'])
        
        # Copy amenities
        amenities = list(room.room_type.amenities.all())
        if amenities:
            room.amenities.set(amenities)

class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0006_roomtypeimage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='amenities',
            field=models.ManyToManyField(blank=True, help_text='Specific amenities for this room', to='rooms.amenity'),
        ),
        migrations.AddField(
            model_name='room',
            name='image',
            field=models.ImageField(blank=True, help_text='Specific image for this room', null=True, upload_to='rooms/'),
        ),
        migrations.AddField(
            model_name='room',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Set a specific price for this room (overrides room type price)', max_digits=10, null=True),
        ),
        migrations.RunPython(copy_room_type_data_to_rooms, reverse_code=migrations.RunPython.noop),
    ]
