# Generated by Django 5.2.17 on 2026-08-13 20:59

import django.db.models.deletion
from django.db import migrations, models
from django.utils.text import slugify


def populate_room_type_slugs(apps, schema_editor):
    RoomType = apps.get_model('rooms', 'RoomType')
    used = set()
    for room_type in RoomType.objects.order_by('pk'):
        base = slugify(room_type.name) or f'room-type-{room_type.pk}'
        slug, suffix = base, 2
        while slug in used:
            slug = f'{base}-{suffix}'
            suffix += 1
        room_type.slug = slug
        room_type.save(update_fields=['slug'])
        used.add(slug)


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0007_room_amenities_room_image_room_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomtype',
            name='slug',
            field=models.SlugField(blank=True, max_length=120),
        ),
        migrations.RunPython(populate_room_type_slugs, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='roomtype', name='slug',
            field=models.SlugField(blank=True, max_length=120, unique=True),
        ),
        migrations.CreateModel(
            name='RoomImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='rooms/gallery/%Y/%m/')),
                ('alt_text', models.CharField(blank=True, max_length=180)),
                ('caption', models.CharField(blank=True, max_length=220)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='rooms.room')),
            ],
            options={
                'ordering': ['display_order', 'id'],
            },
        ),
    ]
