# Generated by Django 4.2.30 on 2026-07-20 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_newslettersubscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsletterMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('cta_text', models.CharField(blank=True, max_length=100)),
                ('cta_link', models.URLField(blank=True)),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='newsletters/')),
                ('recipient', models.CharField(choices=[('all', 'All Subscribers'), ('active', 'Active Subscribers')], default='all', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('ready_to_send', 'Ready to Send')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
