# Generated by Django 4.2.30 on 2026-08-09 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0003_newslettermessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='newslettermessage',
            name='recipient_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='newslettermessage',
            name='sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='newslettermessage',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('ready_to_send', 'Ready to Send'), ('sent', 'Sent')], default='draft', max_length=20),
        ),
    ]
