# Generated by Django 4.2.30 on 2026-08-09 23:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('frontend', '0004_add_newsletter_delivery_tracking'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyMetricSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_date', models.DateField(unique=True)),
                ('currency', models.CharField(default='NGN', max_length=3)),
                ('available_rooms', models.PositiveIntegerField(default=0)),
                ('occupied_rooms', models.PositiveIntegerField(default=0)),
                ('occupancy_percent', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('room_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('service_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('adr', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('revpar', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('receivables', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('cash_variance', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('reservation_sources', models.JSONField(default=dict)),
                ('operational_sla', models.JSONField(default=dict)),
                ('source_hash', models.CharField(max_length=64)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_metric_snapshots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-business_date'],
            },
        ),
        migrations.CreateModel(
            name='ManagementQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('assigned', 'Assigned'), ('investigating', 'Investigating'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='open', max_length=20)),
                ('priority', models.CharField(choices=[('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=20)),
                ('source_model', models.CharField(blank=True, max_length=80)),
                ('source_id', models.CharField(blank=True, max_length=80)),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('resolution', models.TextField(blank=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_management_queries', to=settings.AUTH_USER_MODEL)),
                ('raised_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='raised_management_queries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MetricDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=80, unique=True)),
                ('name', models.CharField(max_length=160)),
                ('description', models.TextField()),
                ('formula', models.TextField()),
                ('unit', models.CharField(max_length=30)),
                ('source_models', models.JSONField(default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='NightAuditRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('business_date', models.DateField(unique=True)),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('reopened', 'Reopened')], default='completed', max_length=20)),
                ('exception_summary', models.JSONField(blank=True, default=dict)),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('reopened_at', models.DateTimeField(blank=True, null=True)),
                ('reopen_reason', models.TextField(blank=True)),
                ('completed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='completed_night_audits', to=settings.AUTH_USER_MODEL)),
                ('reopened_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reopened_night_audits', to=settings.AUTH_USER_MODEL)),
                ('snapshot', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='night_audit', to='frontend.dailymetricsnapshot')),
            ],
            options={
                'ordering': ['-business_date'],
            },
        ),
        migrations.CreateModel(
            name='ManagementQueryNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('evidence', models.FileField(blank=True, null=True, upload_to='management_queries/evidence/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='management_query_notes', to=settings.AUTH_USER_MODEL)),
                ('query', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notes', to='frontend.managementquery')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ManagementQueryHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(blank=True, max_length=20)),
                ('to_status', models.CharField(max_length=20)),
                ('action', models.CharField(max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='management_query_changes', to=settings.AUTH_USER_MODEL)),
                ('query', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='history', to='frontend.managementquery')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
    ]
