# Generated by Django 4.2.30 on 2026-08-10 00:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def seed_configuration(apps, schema_editor):
    FeatureFlag = apps.get_model('frontend', 'FeatureFlag')
    OperationalSetting = apps.get_model('frontend', 'OperationalSetting')
    for key, description in [
        ('public-booking', 'Allow guests to create website quotes and bookings.'),
        ('public-live-chat', 'Show the visitor live-chat widget.'),
        ('online-payments', 'Expose hosted online payment actions after provider approval.'),
    ]:
        FeatureFlag.objects.get_or_create(
            key=key, defaults={'description': description, 'is_enabled': key != 'online-payments'}
        )
    for key, value, description in [
        ('business-hours', {'timezone': 'Africa/Lagos', 'open': '00:00', 'close': '23:59'}, 'Guest-support operating hours.'),
        ('manager-pack-schedule', {'enabled': False, 'time': '07:00'}, 'Daily manager-pack schedule.'),
        ('discount-approval-limits', {'manager': 20, 'admin': 100}, 'Maximum reservation discount percentage by approving role.'),
    ]:
        OperationalSetting.objects.get_or_create(
            key=key, defaults={'value': value, 'description': description}
        )


def unseed_configuration(apps, schema_editor):
    apps.get_model('frontend', 'FeatureFlag').objects.filter(
        key__in=['public-booking', 'public-live-chat', 'online-payments']
    ).delete()
    apps.get_model('frontend', 'OperationalSetting').objects.filter(
        key__in=['business-hours', 'manager-pack-schedule', 'discount-approval-limits']
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('frontend', '0007_add_editable_site_pages'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=80, unique=True)),
                ('description', models.CharField(max_length=255)),
                ('is_enabled', models.BooleanField(default=False)),
                ('roles', models.JSONField(blank=True, default=list, help_text='Empty means all roles.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='OperationalSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=100, unique=True)),
                ('value', models.JSONField(default=dict)),
                ('description', models.CharField(max_length=255)),
                ('is_secret', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='AnalyticsEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.SlugField(max_length=80)),
                ('path', models.CharField(blank=True, max_length=255)),
                ('session_key', models.CharField(blank=True, db_index=True, max_length=40)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('occurred_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analytics_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-occurred_at'],
                'indexes': [models.Index(fields=['event_name', 'occurred_at'], name='frontend_an_event_2d8d89_idx')],
            },
        ),
        migrations.RunPython(seed_configuration, unseed_configuration),
    ]
