# Generated by Django 4.2.30 on 2026-08-10 00:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('frontend', '0008_featureflag_operationalsetting_analyticsevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManagementPack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_date', models.DateField(unique=True)),
                ('metrics', models.JSONField(default=dict)),
                ('booking_pace', models.JSONField(default=dict)),
                ('exceptions', models.JSONField(default=dict)),
                ('pdf_file', models.FileField(upload_to='management_packs/%Y/%m/')),
                ('csv_file', models.FileField(upload_to='management_packs/%Y/%m/')),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_management_packs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-business_date'],
            },
        ),
    ]
