# Generated by Django 4.2.30 on 2026-08-10 02:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0007_bookingquote_extra_total_bookingquoteextra_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('frontend', '0009_managementpack'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocalGuidePlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
                ('category', models.CharField(choices=[('landmark', 'Landmark'), ('dining', 'Dining'), ('shopping', 'Shopping'), ('business', 'Business'), ('transport', 'Transport'), ('wellness', 'Wellness')], max_length=20)),
                ('summary', models.TextField()),
                ('address', models.CharField(blank=True, max_length=255)),
                ('travel_minutes', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('website', models.URLField(blank=True)),
                ('map_url', models.URLField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='local-guide/')),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('is_published', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SitePageTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(help_text='BCP 47 language code, for example en, fr or ha.', max_length=10)),
                ('navigation_title', models.CharField(max_length=80)),
                ('browser_title', models.CharField(max_length=160)),
                ('meta_description', models.CharField(max_length=300)),
                ('hero_eyebrow', models.CharField(blank=True, max_length=100)),
                ('hero_title', models.CharField(blank=True, max_length=180)),
                ('hero_summary', models.TextField(blank=True)),
                ('is_published', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='frontend.sitepage')),
            ],
            options={
                'ordering': ['page', 'language_code'],
            },
        ),
        migrations.CreateModel(
            name='LocalGuidePlaceTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=140)),
                ('summary', models.TextField()),
                ('address', models.CharField(blank=True, max_length=255)),
                ('is_published', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='frontend.localguideplace')),
            ],
        ),
        migrations.CreateModel(
            name='GuestTestimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=100)),
                ('rating', models.PositiveSmallIntegerField()),
                ('body', models.TextField(max_length=1500)),
                ('publication_consent', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', 'Pending review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('moderation_notes', models.CharField(blank=True, max_length=500)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('guest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='testimonials', to=settings.AUTH_USER_MODEL)),
                ('reservation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='testimonials', to='reservations.reservation')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_testimonials', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='sitepagetranslation',
            constraint=models.UniqueConstraint(fields=('page', 'language_code'), name='unique_site_page_translation'),
        ),
        migrations.AddConstraint(
            model_name='localguideplacetranslation',
            constraint=models.UniqueConstraint(fields=('place', 'language_code'), name='unique_guide_place_translation'),
        ),
    ]
