# Generated by Django 4.2.30 on 2026-08-10 05:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('frontend', '0011_tamper_evident_audit_chain'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('booking', 'Booking'), ('stay', 'Your stay'), ('payment', 'Payment'), ('services', 'Hotel services'), ('accessibility', 'Accessibility')], max_length=30)),
                ('question', models.CharField(max_length=220)),
                ('answer', models.TextField()),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('is_published', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['category', 'display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PolicyDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('policy_type', models.CharField(choices=[('privacy', 'Privacy notice'), ('booking', 'Booking terms'), ('cancellation', 'Cancellation policy'), ('cookies', 'Cookie notice'), ('accessibility', 'Accessibility statement'), ('house_rules', 'House rules')], max_length=30)),
                ('title', models.CharField(max_length=180)),
                ('summary', models.CharField(max_length=300)),
                ('body', models.TextField(help_text='Plain text only. Paragraph breaks are preserved safely.')),
                ('version', models.CharField(default='1.0', max_length=30)),
                ('effective_date', models.DateField(blank=True, null=True)),
                ('review_status', models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved')], default='draft', max_length=20)),
                ('review_notes', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('approved_hash', models.CharField(blank=True, editable=False, max_length=64)),
                ('is_published', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviewed_policy_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['policy_type', 'title'],
            },
        ),
    ]
