# Generated by Django 5.2.17 on 2026-08-13 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0013_seed_faq_and_policy_drafts'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillboardContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('subtitle', models.CharField(blank=True, max_length=220)),
                ('body', models.TextField(blank=True)),
                ('content_type', models.CharField(choices=[('brand', 'Brand moment'), ('promotion', 'Promotion'), ('announcement', 'Announcement'), ('service', 'Guest service'), ('tip', 'Guest tip'), ('question', 'Question and answer'), ('trivia', 'Trivia'), ('gallery', 'Gallery'), ('video', 'Video'), ('information', 'Information'), ('celebration', 'Celebration')], max_length=24)),
                ('icon', models.CharField(blank=True, help_text='Existing project icon class.', max_length=80)),
                ('image', models.ImageField(blank=True, null=True, upload_to='billboard/images/%Y/%m/')),
                ('video', models.FileField(blank=True, null=True, upload_to='billboard/video/%Y/%m/')),
                ('fallback_image', models.ImageField(blank=True, null=True, upload_to='billboard/fallbacks/%Y/%m/')),
                ('priority', models.CharField(choices=[('normal', 'Normal'), ('featured', 'Featured'), ('important', 'Important')], default='normal', max_length=12)),
                ('layout_variant', models.CharField(choices=[('cinematic', 'Cinematic'), ('split', 'Split screen'), ('cards', 'Cards'), ('minimal', 'Minimal'), ('broadcast', 'Broadcast'), ('mosaic', 'Mosaic'), ('question', 'Question'), ('keycard', 'Room key card')], default='cinematic', max_length=20)),
                ('transition_variant', models.CharField(choices=[('cinematic', 'Cinematic fade'), ('wipe', 'Gold wipe'), ('curtain', 'Curtain'), ('split', 'Split reveal'), ('iris', 'Iris'), ('blur', 'Blur dissolve'), ('mosaic', 'Mosaic')], default='cinematic', max_length=20)),
                ('duration_seconds', models.PositiveSmallIntegerField(default=10)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('cta_text', models.CharField(blank=True, max_length=80)),
                ('cta_url', models.CharField(blank=True, help_text='Absolute URL or a public site path.', max_length=300)),
                ('start_at', models.DateTimeField(blank=True, null=True)),
                ('end_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-priority', 'display_order', 'id'],
            },
        ),
    ]
