# Generated by Django 5.2.17 on 2026-08-17 16:38

from django.db import migrations


def configure_whatsapp(apps, schema_editor):
    OperationalSetting = apps.get_model('frontend', 'OperationalSetting')
    FeatureFlag = apps.get_model('frontend', 'FeatureFlag')
    OperationalSetting.objects.get_or_create(
        key='whatsapp-contact',
        defaults={
            'value': {
                'number': '2347080076496',
                'message': 'Hello GraceDay Inn, I would like help with a reservation.',
            },
            'description': 'Public WhatsApp contact number and pre-filled greeting.',
            'is_secret': False,
        },
    )
    FeatureFlag.objects.filter(key='public-live-chat').update(
        is_enabled=False,
        description='Retired: public contact is handled through WhatsApp.',
    )


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0014_billboardcontent'),
    ]

    operations = [
        migrations.RunPython(configure_whatsapp, migrations.RunPython.noop),
    ]
