# Generated by Django 5.2.17 on 2026-08-17 16:51

from django.db import migrations


def disable_chat_alert(apps, schema_editor):
    AlertRule = apps.get_model('notifications', 'AlertRule')
    AlertRule.objects.filter(key='chat-unanswered').update(is_enabled=False)


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0015_retire_live_chat_enable_whatsapp'),
        ('notifications', '0010_alertrule_operationalalert_and_more'),
    ]

    operations = [
        migrations.RunPython(disable_chat_alert, migrations.RunPython.noop),
    ]
