# Generated by Django 5.2.17 on 2026-08-17 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0016_disable_retired_chat_alert'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailymetricsnapshot',
            name='operating_expenses',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='dailymetricsnapshot',
            name='operating_profit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
    ]
