# Generated by Django 4.2.30 on 2026-08-09 23:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunicationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=100)),
                ('channel', models.CharField(choices=[('email', 'Email')], default='email', max_length=20)),
                ('locale', models.CharField(default='en', max_length=10)),
                ('version', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('retired', 'Retired')], default='draft', max_length=20)),
                ('subject', models.CharField(max_length=255)),
                ('html_body', models.TextField()),
                ('text_body', models.TextField(blank=True)),
                ('variables_schema', models.JSONField(blank=True, default=dict)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['key', 'locale', '-version'],
            },
        ),
        migrations.CreateModel(
            name='ContactPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('purpose', models.CharField(default='marketing', max_length=50)),
                ('consent_granted', models.BooleanField(default=False)),
                ('consent_source', models.CharField(max_length=100)),
                ('consent_version', models.CharField(blank=True, max_length=50)),
                ('granted_at', models.DateTimeField(blank=True, null=True)),
                ('withdrawn_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Suppression',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('reason', models.CharField(choices=[('unsubscribe', 'Unsubscribe'), ('complaint', 'Complaint'), ('hard_bounce', 'Hard Bounce'), ('invalid', 'Invalid Address'), ('manual', 'Manual')], max_length=30)),
                ('source', models.CharField(default='brevo', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='OutboundMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('purpose', models.CharField(max_length=80)),
                ('recipient_email', models.EmailField(max_length=254)),
                ('recipient_name', models.CharField(blank=True, max_length=160)),
                ('subject', models.CharField(max_length=255)),
                ('html_body', models.TextField()),
                ('text_body', models.TextField(blank=True)),
                ('context', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('processing', 'Processing'), ('accepted', 'Accepted'), ('delivered', 'Delivered'), ('deferred', 'Deferred'), ('failed', 'Failed'), ('bounced', 'Bounced'), ('complained', 'Complained'), ('suppressed', 'Suppressed')], default='queued', max_length=20)),
                ('provider', models.CharField(default='brevo', max_length=30)),
                ('provider_message_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('idempotency_key', models.CharField(max_length=120, unique=True)),
                ('related_model', models.CharField(blank=True, max_length=80)),
                ('related_id', models.CharField(blank=True, max_length=80)),
                ('attempt_count', models.PositiveIntegerField(default=0)),
                ('next_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outbound_messages', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='messages', to='notifications.communicationtemplate')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_event_id', models.CharField(max_length=160, unique=True)),
                ('event_type', models.CharField(choices=[('sent', 'Sent'), ('delivered', 'Delivered'), ('opened', 'Opened'), ('clicked', 'Clicked'), ('deferred', 'Deferred'), ('soft_bounce', 'Soft Bounce'), ('hard_bounce', 'Hard Bounce'), ('blocked', 'Blocked'), ('invalid', 'Invalid'), ('complaint', 'Complaint'), ('unsubscribed', 'Unsubscribed'), ('error', 'Error')], max_length=30)),
                ('provider_message_id', models.CharField(blank=True, max_length=255)),
                ('recipient_email', models.EmailField(blank=True, max_length=254)),
                ('occurred_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='events', to='notifications.outboundmessage')),
            ],
            options={
                'ordering': ['-received_at'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_number', models.PositiveIntegerField()),
                ('outcome', models.CharField(max_length=30)),
                ('response_code', models.PositiveIntegerField(blank=True, null=True)),
                ('provider_message_id', models.CharField(blank=True, max_length=255)),
                ('error_detail', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attempts', to='notifications.outboundmessage')),
            ],
        ),
        migrations.AddConstraint(
            model_name='contactpreference',
            constraint=models.UniqueConstraint(fields=('email', 'purpose'), name='unique_contact_preference'),
        ),
        migrations.AddConstraint(
            model_name='communicationtemplate',
            constraint=models.UniqueConstraint(fields=('key', 'locale', 'version'), name='unique_template_version'),
        ),
        migrations.AddConstraint(
            model_name='deliveryattempt',
            constraint=models.UniqueConstraint(fields=('message', 'attempt_number'), name='unique_delivery_attempt'),
        ),
    ]
