# Generated by Django 4.2.30 on 2026-08-10 00:51

from django.db import migrations, models
import django.db.models.deletion
import uuid
from django.utils import timezone


def seed_jobs(apps, schema_editor):
    ScheduledJob = apps.get_model('notifications', 'ScheduledJob')
    for key, handler, interval in [
        ('email-outbox', 'email_outbox', 1),
        ('expire-inventory-holds', 'expire_inventory_holds', 5),
        ('daily-manager-pack', 'manager_pack', 1440),
    ]:
        ScheduledJob.objects.get_or_create(
            key=key, defaults={
                'handler': handler, 'interval_minutes': interval,
                'next_run_at': timezone.now(), 'is_enabled': True,
            },
        )


def unseed_jobs(apps, schema_editor):
    apps.get_model('notifications', 'ScheduledJob').objects.filter(
        key__in=['email-outbox', 'expire-inventory-holds', 'daily-manager-pack']
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_add_live_chat'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=80, unique=True)),
                ('handler', models.CharField(choices=[('email_outbox', 'Email outbox'), ('expire_inventory_holds', 'Expire inventory holds'), ('manager_pack', 'Generate daily manager pack')], max_length=50)),
                ('interval_minutes', models.PositiveIntegerField(default=5)),
                ('is_enabled', models.BooleanField(default=True)),
                ('next_run_at', models.DateTimeField(db_index=True)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('consecutive_failures', models.PositiveIntegerField(default=0)),
                ('max_failures', models.PositiveIntegerField(default=5)),
                ('last_error', models.CharField(blank=True, max_length=500)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('locked_by', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['next_run_at', 'key'],
            },
        ),
        migrations.CreateModel(
            name='JobExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], default='running', max_length=20)),
                ('worker_id', models.CharField(max_length=100)),
                ('result', models.JSONField(blank=True, default=dict)),
                ('error', models.CharField(blank=True, max_length=500)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='executions', to='notifications.scheduledjob')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.RunPython(seed_jobs, unseed_jobs),
    ]
