# Generated by Django 4.2.30 on 2026-08-10 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0006_inquiryroutingrule_inquiryattachment'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatOperatingHour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.PositiveSmallIntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], unique=True)),
                ('opens_at', models.TimeField(default='08:00')),
                ('closes_at', models.TimeField(default='22:00')),
                ('is_closed', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['weekday'],
            },
        ),
        migrations.AddField(
            model_name='chatconversation',
            name='is_offline_capture',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chatconversation',
            name='satisfaction_comment',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='chatconversation',
            name='satisfaction_rating',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chatconversation',
            name='satisfaction_submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
