# Generated by Django 4.2.30 on 2026-08-10 01:52

from django.db import migrations, models
from django.utils import timezone


def seed_contact_sync_job(apps, schema_editor):
    apps.get_model('notifications', 'ScheduledJob').objects.get_or_create(
        key='brevo-contact-sync',
        defaults={
            'handler': 'brevo_contact_sync', 'interval_minutes': 15,
            'next_run_at': timezone.now(), 'is_enabled': True,
        },
    )


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0007_chatoperatinghour_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrevoContactSync',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('synced', 'Synced'), ('deferred', 'Deferred'), ('failed', 'Failed'), ('suppressed', 'Suppressed')], default='pending', max_length=20)),
                ('desired_marketing_consent', models.BooleanField(default=False)),
                ('attempt_count', models.PositiveIntegerField(default=0)),
                ('provider_contact_id', models.CharField(blank=True, max_length=80)),
                ('last_error', models.CharField(blank=True, max_length=500)),
                ('next_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['status', 'email'],
            },
        ),
        migrations.AlterField(
            model_name='scheduledjob',
            name='handler',
            field=models.CharField(choices=[('email_outbox', 'Email outbox'), ('brevo_contact_sync', 'Brevo contact synchronization'), ('expire_inventory_holds', 'Expire inventory holds'), ('manager_pack', 'Generate daily manager pack')], max_length=50),
        ),
        migrations.RunPython(seed_contact_sync_job, migrations.RunPython.noop),
    ]
