# Generated by Django 4.2.30 on 2026-08-10 03:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid
from django.utils import timezone


def seed_operational_alerts(apps, schema_editor):
    AlertRule = apps.get_model('notifications', 'AlertRule')
    ScheduledJob = apps.get_model('notifications', 'ScheduledJob')
    defaults = [
        ('room-state', 'Room-state reconciliation', 'room_state', 'critical', 5, ['admin', 'manager', 'receptionist'], {}),
        ('housekeeping-overdue', 'Overdue housekeeping', 'overdue_housekeeping', 'high', 120, ['admin', 'manager', 'housekeeping'], {}),
        ('maintenance-overdue', 'Overdue maintenance', 'overdue_maintenance', 'high', 240, ['admin', 'manager'], {}),
        ('chat-unanswered', 'Unanswered live chat', 'unanswered_chat', 'high', 10, ['admin', 'manager', 'receptionist'], {}),
        ('inquiry-sla', 'Inquiry SLA breach', 'inquiry_sla', 'high', 60, ['admin', 'manager', 'receptionist'], {}),
        ('job-failures', 'Scheduled job failures', 'job_failure', 'critical', 5, ['admin', 'manager'], {'failure_count': 2}),
    ]
    for key, name, rule_type, severity, threshold, roles, configuration in defaults:
        AlertRule.objects.get_or_create(key=key, defaults={
            'name': name, 'rule_type': rule_type, 'severity': severity,
            'threshold_minutes': threshold, 'recipient_roles': roles,
            'configuration': configuration,
        })
    ScheduledJob.objects.get_or_create(key='domain-alerts', defaults={
        'handler': 'domain_alerts', 'interval_minutes': 5,
        'next_run_at': timezone.now(), 'max_failures': 5,
    })


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notifications', '0009_chatcannedreply'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=80, unique=True)),
                ('name', models.CharField(max_length=160)),
                ('rule_type', models.CharField(choices=[('room_state', 'Room-state discrepancy'), ('overdue_housekeeping', 'Overdue housekeeping'), ('overdue_maintenance', 'Overdue maintenance'), ('unanswered_chat', 'Unanswered live chat'), ('inquiry_sla', 'Inquiry SLA breach'), ('job_failure', 'Scheduled-job failures')], max_length=40)),
                ('is_enabled', models.BooleanField(default=True)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('high', 'High'), ('critical', 'Critical')], default='warning', max_length=20)),
                ('threshold_minutes', models.PositiveIntegerField(default=60)),
                ('recipient_roles', models.JSONField(blank=True, default=list)),
                ('configuration', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['key'],
            },
        ),
        migrations.CreateModel(
            name='OperationalAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('dedupe_key', models.CharField(max_length=180, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('detail', models.TextField()),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('high', 'High'), ('critical', 'Critical')], max_length=20)),
                ('status', models.CharField(choices=[('open', 'Open'), ('acknowledged', 'Acknowledged'), ('resolved', 'Resolved')], default='open', max_length=20)),
                ('source_model', models.CharField(max_length=80)),
                ('source_id', models.CharField(max_length=80)),
                ('link', models.CharField(blank=True, max_length=200)),
                ('occurrence_count', models.PositiveIntegerField(default=1)),
                ('first_detected_at', models.DateTimeField(auto_now_add=True)),
                ('last_detected_at', models.DateTimeField(auto_now_add=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_notes', models.CharField(blank=True, max_length=500)),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_operational_alerts', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_operational_alerts', to=settings.AUTH_USER_MODEL)),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alerts', to='notifications.alertrule')),
            ],
            options={
                'ordering': ['status', '-severity', '-last_detected_at'],
            },
        ),
        migrations.AlterField(
            model_name='scheduledjob',
            name='handler',
            field=models.CharField(choices=[('email_outbox', 'Email outbox'), ('brevo_contact_sync', 'Brevo contact synchronization'), ('expire_inventory_holds', 'Expire inventory holds'), ('manager_pack', 'Generate daily manager pack'), ('domain_alerts', 'Evaluate operational alert rules')], max_length=50),
        ),
        migrations.CreateModel(
            name='OperationalAlertHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=30)),
                ('from_status', models.CharField(blank=True, max_length=20)),
                ('to_status', models.CharField(max_length=20)),
                ('notes', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operational_alert_actions', to=settings.AUTH_USER_MODEL)),
                ('alert', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='history', to='notifications.operationalalert')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.RunPython(seed_operational_alerts, migrations.RunPython.noop),
    ]
